"""updated kcal_out by making duration nullable

Revision ID: 18caf090c8d1
Revises: 86a1e2d82486
Create Date: 2024-06-01 13:30:10.808412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18caf090c8d1'
down_revision = '86a1e2d82486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kcal_out', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kcal_out', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=False)

    # ### end Alembic commands ###
