"""Added meal date field to kcal_in

Revision ID: 2cd0b363cee8
Revises: 
Create Date: 2024-06-01 00:08:31.452923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2cd0b363cee8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kcal_in', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('meal_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kcal_in', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('meal_date')

    # ### end Alembic commands ###
