"""updated kcal_outs kcal_out field to allow for percision 7,2 instead of 6,2

Revision ID: 472e4813757d
Revises: 18caf090c8d1
Create Date: 2024-06-04 23:58:07.451683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472e4813757d'
down_revision = '18caf090c8d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitbit_account', schema=None) as batch_op:
        batch_op.drop_column('refresh_token')

    with op.batch_alter_table('kcal_out', schema=None) as batch_op:
        batch_op.alter_column('kcal_out',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kcal_out', schema=None) as batch_op:
        batch_op.alter_column('kcal_out',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('fitbit_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
