"""updated kcal_out field activity_nm to activity_id

Revision ID: 86a1e2d82486
Revises: 424dc51443e2
Create Date: 2024-06-01 13:17:53.168514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a1e2d82486'
down_revision = '424dc51443e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kcal_out', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('kcal_out_activity_nm_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'activity', ['activity_id'], ['id'])
        batch_op.drop_column('activity_nm')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kcal_out', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_nm', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('kcal_out_activity_nm_fkey', 'activity', ['activity_nm'], ['id'])
        batch_op.drop_column('activity_id')

    # ### end Alembic commands ###
