"""Added ref_filename column to kcal_in

Revision ID: c4680248d230
Revises: 472e4813757d
Create Date: 2024-06-06 23:14:27.988340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4680248d230'
down_revision = '472e4813757d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kcal_in', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ref_filename', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kcal_in', schema=None) as batch_op:
        batch_op.drop_column('ref_filename')

    # ### end Alembic commands ###
